In [28]:
import torch

In [29]:
t = torch.tensor([[1, 2, 3, 4], [5, 6, 7, 8]])

In [34]:
a = t
b = t.T

In [35]:
print(a)
print(b)

tensor([[1, 2, 3, 4],
        [5, 6, 7, 8]])
tensor([[1, 5],
        [2, 6],
        [3, 7],
        [4, 8]])


In [36]:
a * b

RuntimeError: The size of tensor a (4) must match the size of tensor b (2) at non-singleton dimension 1

In [37]:
a @ b

tensor([[ 30,  70],
        [ 70, 174]])

In [25]:
# a * b 和 a @ b 的区别
# a * b 是对应位置相乘
# a @ b 是矩阵乘法
# torch.mm(a, b) 也是矩阵乘法